import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin Ositha',
      email: 'admin@test.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'User Dewruwan',
      email: 'user@test.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike T- Shirt',
      category: 'shirt',
      image: '/img/products/p1.jpg',
      price: 120,
      brand: 'Nike',
      rating: 1,
      numReviews: 10,
      countInStock: 10,
      description: 'High Quality Products',
    },
    {
      name: 'Nike T- Shirt 2',
      category: 'shirt',
      image: '/img/products/p2.jpg',
      price: 120,
      brand: 'Nike',
      rating: 1.5,
      numReviews: 10,
      countInStock: 10,
      description: 'High Quality Products',
    },
    {
      name: 'Nike T- Shirt 3',
      category: 'shirt',
      image: '/img/products/p3.jpg',
      price: 90,
      brand: 'Nike',
      rating: 2,
      numReviews: 10,
      countInStock: 0,
      description: 'High Quality Products',
    },
    {
      name: 'Nike T- Shirt 4',
      category: 'shirt',
      image: '/img/products/p4.jpg',
      price: 582,
      brand: 'Nike',
      rating: 2.5,
      numReviews: 10,
      countInStock: 10,
      description: 'High Quality Products',
    },
    {
      name: 'Nike T- Shirt 5',
      category: 'shirt',
      image: '/img/products/p5.jpg',
      price: 157,
      brand: 'Nike',
      rating: 3,
      numReviews: 10,
      countInStock: 10,
      description: 'High Quality Products',
    },
    {
      name: 'Nike T- Shirt 6',
      category: 'shirt',
      image: '/img/products/p6.jpg',
      price: 220,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 15,
      countInStock: 10,
      description: 'High Quality Products',
    },

    {
      name: 'Nike T- Shirt 7',
      category: 'shirt',
      image: '/img/products/p7.jpg',
      price: 220,
      brand: 'Nike',
      rating: 4,
      numReviews: 5,
      countInStock: 200,
      description: 'High Quality Products',
    },

    {
      name: 'Nike T- Shirt 8',
      category: 'shirt',
      image: '/img/products/p8.jpg',
      price: 90,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 12,
      countInStock: 12,
      description: 'High Quality Products',
    },
  ],
};

export default data;
