const data = {
    products: [
        {
            _id: '1',
            name: 'Nike T- Shirt',
            category: 'shirt',
            image: '/img/products/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Products',
        },
        {
            _id: '2',
            name: 'Nike T- Shirt 2',
            category: 'shirt',
            image: '/img/products/p2.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Products',
        },
        {
            _id: '3',
            name: 'Nike T- Shirt 3',
            category: 'shirt',
            image: '/img/products/p3.jpg',
            price: 90,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Products',
        },
        {
            _id: '4',
            name: 'Nike T- Shirt 4',
            category: 'shirt',
            image: '/img/products/p4.jpg',
            price: 582,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Products',
        },
        {
            _id: '5',
            name: 'Nike T- Shirt 5',
            category: 'shirt',
            image: '/img/products/p5.jpg',
            price: 157,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Products',
        },
        {
            _id: '6',
            name: 'Nike T- Shirt 6',
            category: 'shirt',
            image: '/img/products/p6.jpg',
            price: 220,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 15,
            description: 'High Quality Products',
        },

        {
            _id: '7',
            name: 'Nike T- Shirt 7',
            category: 'shirt',
            image: '/img/products/p7.jpg',
            price: 220,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 5,
            description: 'High Quality Products',
        },

        {
            _id: '8',
            name: 'Nike T- Shirt 8',
            category: 'shirt',
            image: '/img/products/p8.jpg',
            price: 220,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 12,
            description: 'High Quality Products',
        },


    ],
};

export default data;